### ISSUE TITLE
Slightly confusing hoon documentation

### ISSUE THREAD

**Issue by ronreg-ribdev** [urbit/docs#744]
On https://urbit.org/docs/tutorials/hoon/conditionals/ , there is an example of a hoon program - the first example of a %say generator -  but no instructions about what to name it, how to actually run it in a dojo environment, and what output should be expected. Someone who's already gone through the previous tutorial pages can probably figure out that they need to name it `something.hoon`, and run it with `+something`, but the docs would be nicer for people still trying to figure out how hoon works if this was clearly spelled out on that page.

**Comment by drbeefsupreme** [comment]
So this page is out of date, this should be https://github.com/urbit/docs/pull/728/commits/b837b4549a8503db51185769dc76e38175058f27 I'm not sure why it hasn't been pushed to the site yet.

I've thought about this for a few days, but I have to disagree. Anybody should expect that if they jump ahead in numbered lessons there are going to be things that they missed that are being referenced. While we do repeat some concepts in the tutorial, in this case the missed information is on the "1.1 Setup" page. If someone is skipping setup then they probably aren't really interested in running the software anyways (at least not yet) so that information won't be relevant to them.

**Comment by drbeefsupreme** [comment]
Oops, I meant to link urbit/docs#728

**Comment by drbeefsupreme** [comment]
As there have been no further comments, I'm closing this, but feel free to re-open it if you disagree with my reasoning above.
